language: node_js
node_js:
  - 0.10
  - 0.8
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "echo 'Installing Slimer'"
  - "wget http://download.slimerjs.org/v0.8/slimerjs-0.8.3.zip"
  - "unzip slimerjs-0.8.3.zip"
  - "mv slimerjs-0.8.3 ./slimerjs"
  - npm install nws -g
  - nws -p 9292 &
  - sleep 5
script: grunt test --verbose --force && mocha && phantomjs test/ui/xf.ui.button.js http://localhost:9292/test/test.html && phantomjs test/ui/xf.ui.fieldset.js http://localhost:9292/test/test.html && phantomjs test/ui/xf.ui.dialog.js http://localhost:9292/test/test.html && phantomjs test/ui/xf.ui.list.js http://localhost:9292/test/test.html
